FROM node:22-alpine

WORKDIR /app

# Copy package info
COPY package*.json ./
RUN npm ci --production

# Copy built app
COPY dist/ ./dist/

# Copy config etc if needed
COPY .env* ./

ENV NODE_ENV=production
ENV PORT=8080

EXPOSE 8080
CMD ["npm", "run", "start"]
